class Item < ActiveHash::Base
  self.data = [
    {id: 1, name: 'チベットスナギツネ'},
    {id: 2, name: 'キャンディ'},
    {id: 3, name: 'クルーザー'},
    {id: 4, name: 'コイン'},
    {id: 5, name: 'ルビーの指輪'},
    {id: 6, name: 'あんぱん'},
    {id: 7, name: '自転車'},
    {id: 8, name: 'ブランドバッグ'},
    {id: 9, name: '紙袋'},
    {id: 10, name: 'カードキー'},
    {id: 11, name: 'ロープ'},
    {id: 12, name: '麦わら帽子'},
    {id: 13, name: 'コーヒー'},
    {id: 14, name: '座布団'},
    {id: 15, name: '口紅'},
    {id: 16, name: '札束'},
    {id: 17, name: '花火'},
    {id: 18, name: '仏像'},
    {id: 19, name: 'バール'},
    {id: 20, name: 'おもちゃのピアノ'},
    {id: 21, name: '芝刈り機'},
    {id: 22, name: 'ライダースジャケット'},
    {id: 23, name: '折り畳み傘'},
    {id: 24, name: '物干し竿'},
    {id: 25, name: 'コーラ'},
    {id: 26, name: 'フライパン'},
    {id: 27, name: 'Tシャツ'},
    {id: 28, name: 'スマホ'},
    {id: 29, name: 'バケツ'},
    {id: 30, name: 'カブトムシ'}
  ]
end